### ISSUE TITLE
Fout bij form submitten contentfull

### ISSUE THREAD

**Issue by ralphbourgoo** [ralphbourgoo/dev4-makeitpersonal#1]
In mijn component "AddCard" probeer ik een formulier te submitten naar contentful. Wat doe ik verkeerd? Ik heb al verschillende recources geraadpleegd, maar geen enkele toont mij de juiste info. Er is weinig over te vindeen.  Ik weet niet hoe ik dit moet doen. Kunnen jullie mij hierbij helpen?

**Comment by SimonVanherweghe** [comment]
Gelieve permalinks naar de stukken code te gebruiken aub.

Hier geef je de data door naar een onSubmit functie, maar die heb je nergens staan
https://github.com/ralphbourgoo/dev4-makeitpersonal/blob/f4fcbe0d21ab1892a2e851c452fa02f75213b8a4/components/AddCard.js#L65

Je maakt een nieuwe entry aan in de `getStaticProps`, dit staat daar niet op z'n plaats
https://github.com/ralphbourgoo/dev4-makeitpersonal/blob/f4fcbe0d21ab1892a2e851c452fa02f75213b8a4/components/AddCard.js#L4-L14

Next roept getStaticProps aan at build time, bij het aanmaken van een statische versie van die pagina. Deze functie kan niet uitgevoerd worden door een actie op de client.

Wat je moet doen:

- Maak een API route aan in Nextjs (onder pages/api/...)
- Doe een fetch post naar die route, en geef de invoerde data mee in de body
- Pas in die api route maak je een contentful client aan (anders kan iedereen aan jouw contentful api tokens) en maak je een entry aan.

Dit is eigenlijk gelijkaardig als de buttondown integratie vanuit de video topics. Iemand inschrijven is voor een mailinglist of een item aanmaken in contentful: dat is dezelfde werkwijze
