### ISSUE TITLE
Failed image upload

### ISSUE THREAD

**Issue by ralphbourgoo** [ralphbourgoo/dev4-makeitpersonal#2]
In de component AddCard.js probeer ik in het formulier een image up te loaden om door te sturen naar Contentful. Die geef ik ook mee in de handleSubmit. Als ik in de api send.js ook de image meegeef, dan crashed hij. Wat doe ik fout? Kan je op deze manier een image meegeven in contentful? 

Ik heb geprobeerd een permalink toe te voegen, maar het lukt niet. 

Excuses hiervoor.

**Comment by SimonVanherweghe** [comment]
Ik heb geen ervaring met bestanden uploaden naar contentful.
Er zijn wel zaken over te vinden in de documentatie. https://www.contentful.com/blog/2017/03/02/uploading-files-directly-to-contentful/
