### ISSUE TITLE
Vercel Fout

### ISSUE THREAD

**Issue by ralphbourgoo** [ralphbourgoo/dev4-makeitpersonal#3]
Beste, 

Mijn app werkt perfect lokaal. Ik krijg mijn image binnen van Cloudinary en ook als ik ze verstuur en een unieke pagina wordt gerenderd. Ik doe dit door een url op te halen uit de response van mijn Cloudinary Image. 

Als ik naar github push, om mijn applicatie op vercel up te daten, dan krijg ik een foutmelding die zegt: "TypeError: Cannot read property 'url' of null". Lokaal krijg ik dit niet. Alsk ik het console.log dan krijg ik wel de url binnen en wordt mijn Image getoond.

Hoe kan ik dit oplossen? 

<img width="976" alt="Screenshot 2021-04-30 at 11 23 43" src="https://user-images.githubusercontent.com/56590698/116675845-8e2e5b00-a9a6-11eb-8788-10aea1bb74eb.png">

**Comment by SimonVanherweghe** [comment]
Heb je lokaal al eens een 'yarn build' gerund, krijg je dan fouten?

Let er op dat getStaticProps & getStaticPaths in development voor *elke request* runnen, in production enkel at build time.
Ik gok er op dat dit hier het probleem is, je maakt een nieuwe pagina aan, maar deze is nog niet static beschikbaar.
Je gebruikt wel fallback:true, maar je moet nog op de pagina zelf kijken of het over een fallback pagina gaat en dan een loading state tonen. Zie de documentatie en de topics video hierover
